{
 "title": "Gaiad Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Node Status",
   "type": "vonage-status-panel",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "up",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "gaiad_up{job=\"gaiad\"}",
     "legendFormat": "up",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 0.1
    },
    {
     "aggregation": "Last",
     "alias": "peers",
     "crit": 2,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "gaiad_peer_count{job=\"gaiad\"}",
     "legendFormat": "peers",
     "units": "short",
     "valueHandler": "Number Threshold",
     "warn": 5
    }
   ]
  },
  {
   "title": "Network Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gaiad_peer_count{job=\"gaiad\"}"
    }
   ]
  },
  {
   "title": "Last Block",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gaiad_current_block{job=\"gaiad\"}"
    }
   ]
  },
  {
   "title": "Gaiad Block",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gaiad_current_block{job=\"gaiad\"}",
     "legendFormat": "Current Block"
    },
    {
     "expr": "rate(gaiad_current_block{job=\"gaiad\"}[$__interval])",
     "legendFormat": "Block Rate"
    }
   ]
  },
  {
   "title": "Gaiad Block Time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "gaiad_time_deviation{job=\"gaiad\"}",
     "legendFormat": "Current Block"
    }
   ]
  },
  {
   "title": "Gaiad Peers",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gaiad_peer_count{job=\"gaiad\"}",
     "legendFormat": "Peers"
    },
    {
     "expr": "rate(gaiad_peer_count{job=\"gaiad\"}[$__interval])",
     "legendFormat": "Rate"
    }
   ]
  }
 ]
}